In [1]:
import numpy as np;


In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
a = [1,2.3,"hello"]
a

[1, 2.3, 'hello']

In [4]:
np.array(a)

array(['1', '2.3', 'hello'], dtype='<U32')

In [5]:
l = np.array([1,2,3],[5,6,7],[9,5,6])
l

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [6]:
l = [[1,2,3],[4,5,6],[7,8,9]]
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [11]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [13]:
ar = np.zeros((6,6))
ar

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [15]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
arr = np.linspace(1,5,4)
arr

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [17]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [18]:
arr = np.linspace(1,2,100)
arr

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

In [19]:
arr = np.random.rand(10)
arr

array([0.93554365, 0.59256422, 0.27815202, 0.25445618, 0.70669402,
       0.84328886, 0.67265089, 0.89703227, 0.87673688, 0.95705169])

In [25]:
arr = np.random.randn(10)
arr

array([-1.6943247 , -0.10331409, -2.09186194, -0.37614847, -0.27456251,
        1.63366784, -0.52376593, -0.09396741,  0.02127656, -0.20816042])

In [26]:
arr = np.random.randint(1,20,10)
arr

array([16,  1, 14, 16, 12,  8,  9,  4,  3,  4], dtype=int32)

In [27]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr.shape

(3, 3)

In [29]:
arr.size

9

In [30]:
arr.dtype

dtype('int64')