In [1]:
import numpy as np


In [2]:
np.arange(11,21)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[1]
arr[9]

np.int64(20)

In [5]:
arr[1]

np.int64(12)

In [6]:
np.arange(1,30)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [7]:
arr= np.arange(1,30).reshape(6,5)

ValueError: cannot reshape array of size 29 into shape (6,5)

In [8]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [9]:
arr[5]

array([26, 27, 28, 29, 30])

In [10]:
arr[0,0]

np.int64(1)

In [11]:
arr[0,4]

np.int64(5)

In [12]:
arr[5,4]

np.int64(30)

In [13]:
slice = arr[0:2,1:3]

In [14]:
slice

array([[2, 3],
       [7, 8]])

In [15]:
slice = arr[3:6,3:5]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [16]:
slice = arr[3:,2]
slice

array([18, 23, 28])

In [ ]:
slice = arr[3: ,3: ]

In [18]:
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [19]:
arr[: ,2]

array([ 3,  8, 13, 18, 23, 28])