In [1]:
import numpy as np

In [2]:
arr = np.arange(1,11)

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[1:5]

array([2, 3, 4, 5])

In [5]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[1::4]

array([ 2,  6, 10])