In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])


In [3]:
a3 = a1+a2
a3

array([ 7,  9, 11, 13, 15])

In [4]:
a4 = a1-a2
a4

array([-5, -5, -5, -5, -5])

In [5]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [6]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
a1//a2

array([0, 0, 0, 0, 0])

In [8]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [9]:
l = [10,20,30,40,50]
arr = np.array(l)
arr+10

array([20, 30, 40, 50, 60])

In [11]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [13]:
a = np.arange(1,21).reshape(5,4)

In [14]:
slice  = a[:5]

In [15]:
slice * 10
slice

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [16]:
slice = a[:5]
slice = slice*10

In [17]:
slice

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160],
       [170, 180, 190, 200]])

In [18]:
slice = a[:5]

In [19]:
slice = a[:5]
slice = slice * 10
slice


array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160],
       [170, 180, 190, 200]])

In [20]:
a = np.arangee(1,21)
a

AttributeError: module 'numpy' has no attribute 'arangee'

In [21]:
a = np.arange(1,21)

In [22]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
slic = a[:5]

In [24]:
slic = slic * 10

In [25]:
slic

array([10, 20, 30, 40, 50])

In [26]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
a[4:6]*10

array([50, 60])

In [28]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
b = a.copy

In [34]:
a


array([12,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
b[0] = 12

TypeError: 'builtin_function_or_method' object does not support item assignment

In [36]:
a


array([12,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [37]:
b = a.copy

In [38]:
aa = np.arange(1,21)

In [39]:
bb = aa.copy

In [43]:
bb[0] = 12

TypeError: 'builtin_function_or_method' object does not support item assignment

In [41]:
aa

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [42]:
bb[0] = 12

TypeError: 'builtin_function_or_method' object does not support item assignment