In [2]:
import numpy as np

In [3]:
A = np.array([[1,2],[4,5]])
B = np.array([[5,6],[7,8]])

In [4]:
A

array([[1, 2],
       [4, 5]])

In [5]:
B

array([[5, 6],
       [7, 8]])

In [7]:
A @ B

array([[19, 22],
       [55, 64]])

In [8]:
A.T

array([[1, 4],
       [2, 5]])

In [9]:
B.T

array([[5, 7],
       [6, 8]])